### ISSUE TITLE
class for showing the red rectangle for face detection

### ISSUE THREAD

**Issue by mahdidham** [christopherhelf/iOS-Metal-HaarCascade#2]
Hi, I just want to know. How to get the red rectangle (face detection frame) coordinate? i want to use it for segmentation. sorry i ask you in this issue comment

**Comment by christopherhelf** [comment]
Hey there, I haven't worked on this in quite a time, but the detected face rectangles are stored in the `HaarDetection` class, and you can see how they are used in the `createDrawPipeline` which basically puts them on the screen via a buffer `self.groupingParameters.rectanglesBuffer.buffer`, so that's where the coordinates are stored as `float4` values - check out `HaarCascadeDraw.metal` on how they are drawn on screen.

I'm closing the issue - feel free to reopen in case anything comes up.

**Comment by mahdidham** [comment]
can I have your email? I want to more discuss about this filter for my project research. Thanks @christopherhelf
